use crate::{package_cli, runtime_debug};
use serde_json::{Value, json};

pub(crate) fn command_capabilities() -> Vec<Value> {
    let mut commands = vec![
        command_cap("version", ["offline"], "available"),
        command_cap("doctor", ["offline"], "available"),
        command_cap("paths", ["offline"], "available"),
        command_cap("config get", ["offline"], "available"),
        command_cap("config set", ["offline"], "available"),
        command_cap("schema", ["offline"], "available"),
        command_cap("list", ["offline"], "available"),
        command_cap("capabilities", ["offline"], "available"),
        command_cap("resource validate", ["offline"], "available"),
        command_cap("resource convert", ["offline"], "available"),
        command_cap("resource import-alas", ["offline"], "reserved"),
        command_cap("resource drift-alas", ["offline"], "reserved"),
        command_cap("resource check-release", ["offline"], "available"),
        command_cap("observe", ["offline", "device_optional"], "available"),
        command_cap(
            "do",
            ["offline", "device_optional", "lab_lease"],
            "available",
        ),
        command_cap(
            "ensure",
            ["offline", "device_optional", "lab_lease"],
            "available",
        ),
        command_cap("wait", ["offline", "device_optional"], "available"),
        command_cap("package validate", ["offline"], "available"),
        command_cap("package inspect", ["offline"], "available"),
        package_cli::offline_capability(),
        command_cap("package build-task", ["offline"], "available"),
        command_cap("package build-pack", ["offline"], "available"),
        command_cap("ledger show", ["offline", "read_only"], "available"),
        command_cap("ledger events", ["offline", "read_only"], "available"),
        command_cap("ledger receipts", ["offline", "read_only"], "available"),
        command_cap("ledger diagnose", ["offline", "read_only"], "available"),
        command_cap("ledger evidence", ["offline", "read_only"], "available"),
        command_cap("operation validate", ["offline"], "available"),
        command_cap("operation inspect", ["offline"], "available"),
        command_cap("operation explain", ["offline"], "available"),
        command_cap("status", ["running_runtime"], "available"),
        command_cap("run summary", ["running_runtime", "read_only"], "available"),
        command_cap("devices", ["device"], "available"),
        command_cap("touch-probe", ["device"], "available"),
        command_cap("tap", ["device"], "available"),
        command_cap("swipe", ["device"], "available"),
        command_cap("long-tap", ["device"], "available"),
        command_cap("key", ["device"], "available"),
        command_cap("text", ["device"], "available"),
        command_cap("session status", ["offline"], "available"),
        command_cap("session bootstrap", ["offline"], "available"),
        command_cap("session throat-policy", ["offline"], "available"),
        command_cap("session capture-policy", ["offline"], "available"),
        command_cap("session record-policy", ["offline"], "available"),
        command_cap("session self-heal-policy", ["offline"], "available"),
        command_cap("session self-heal-plan", ["offline"], "available"),
        command_cap("session phase-c-plan", ["offline"], "available"),
        command_cap("session readiness", ["offline"], "available"),
        command_cap("session connect-plan", ["offline"], "available"),
        command_cap("session stream-plan", ["offline"], "available"),
        command_cap("session queue", ["offline"], "available"),
        command_cap("session command-check", ["offline"], "available"),
        command_cap("session submit-plan", ["offline"], "available"),
        command_cap("session validation-plan", ["offline"], "available"),
        command_cap("session start", ["offline"], "available"),
        command_cap("session stop", ["offline"], "available"),
        command_cap("session cleanup", ["offline"], "available"),
        command_cap("session journal", ["offline"], "available"),
        command_cap("session events", ["offline"], "available"),
        command_cap("session events wait", ["offline"], "available"),
        command_cap("session response", ["offline"], "available"),
        command_cap("session response get", ["offline"], "available"),
        command_cap("session response wait", ["offline"], "available"),
        command_cap("session request-state", ["offline"], "available"),
        command_cap("session request-state get", ["offline"], "available"),
        command_cap("session request-state wait", ["offline"], "available"),
        command_cap("session request-state list", ["offline"], "available"),
        command_cap("session contract", ["offline"], "available"),
        command_cap("session api", ["offline"], "available"),
        command_cap("session transport", ["offline"], "available"),
        command_cap("session transport plan", ["offline"], "available"),
        command_cap("session transport check", ["offline"], "available"),
        command_cap("session stream", ["offline"], "available"),
        command_cap("session stream check", ["offline"], "available"),
        command_cap("session monitor-policy", ["offline"], "available"),
        command_cap("session request cancel", ["offline"], "available"),
        command_cap("session request status", ["running_runtime"], "available"),
        command_cap(
            "session request bootstrap",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request throat-policy",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request capture-policy",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request record-policy",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request self-heal-policy",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request self-heal-plan",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request phase-c-plan",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request readiness",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request connect-plan",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request stream-plan",
            ["running_runtime"],
            "available",
        ),
        command_cap("session request queue", ["running_runtime"], "available"),
        command_cap(
            "session request command-check",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request submit-plan",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request validation-plan",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request --no-wait",
            ["running_runtime"],
            "available",
        ),
        command_cap("session request journal", ["running_runtime"], "available"),
        command_cap("session request events", ["running_runtime"], "available"),
        command_cap(
            "session request events wait",
            ["running_runtime"],
            "available",
        ),
        command_cap("session request response", ["running_runtime"], "available"),
        command_cap(
            "session request response get",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request response wait",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request request-state",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request request-state get",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request request-state wait",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request request-state list",
            ["running_runtime"],
            "available",
        ),
        command_cap("session request contract", ["running_runtime"], "available"),
        command_cap("session request api", ["running_runtime"], "available"),
        command_cap(
            "session request transport",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request transport plan",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request transport check",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request capabilities",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request monitor-policy",
            ["running_runtime"],
            "available",
        ),
        command_cap("session request devices", ["running_runtime"], "available"),
        command_cap("session request record", ["running_runtime"], "available"),
        command_cap(
            "session request capture",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request capture-diagnose",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request stream",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request stream check",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request recognize",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request detect-page",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request current-page",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request is-visible",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request locate",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request monitor",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request monitor-once",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap(
            "session request instance list",
            ["running_runtime"],
            "available",
        ),
        command_cap(
            "session request instance registry",
            ["running_runtime"],
            "available",
        ),
        command_cap("session request instance health", ["offline"], "retired"),
        command_cap(
            "session request instance keep-alive",
            ["offline"],
            "retired",
        ),
        command_cap("session request instance connect", ["offline"], "retired"),
        command_cap("session request instance reconnect", ["offline"], "retired"),
        command_cap(
            "session request instance app",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request app",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request lab-run",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request package-run",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request operation-run",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request tap",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request swipe",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request long-tap",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request key",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request text",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request tap-target",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request navigate",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request recover",
            ["running_runtime", "device", "lab_lease"],
            "available",
        ),
        command_cap(
            "session request recover --stale-capture",
            ["running_runtime", "device"],
            "available",
        ),
        command_cap("session instance", ["offline", "device"], "available"),
        command_cap("session instance list", ["offline"], "available"),
        command_cap("session instance registry", ["offline"], "available"),
        command_cap("session instance health", ["offline"], "retired"),
        command_cap("session instance keep-alive", ["offline"], "retired"),
        command_cap("session instance connect", ["offline"], "retired"),
        command_cap("session instance reconnect", ["offline"], "retired"),
        command_cap("session instance app", ["device"], "available"),
        command_cap("session instance app launch", ["device"], "available"),
        command_cap("session instance app stop", ["device"], "available"),
        command_cap("session instance app force-stop", ["device"], "available"),
        command_cap("session instance app restart", ["device"], "available"),
        command_cap("session app", ["device"], "available"),
        command_cap("session app launch", ["device"], "available"),
        command_cap("session app stop", ["device"], "available"),
        command_cap("session app force-stop", ["device"], "available"),
        command_cap("session app restart", ["device"], "available"),
        command_cap("session capture", ["device"], "available"),
        command_cap("session capture diagnose", ["device"], "available"),
        command_cap("session recover", ["device"], "available"),
        command_cap("session recover --stale-capture", ["device"], "available"),
        command_cap(
            "session lease run",
            ["running_runtime", "lab_lease"],
            "available",
        ),
        command_cap("session record", ["offline"], "available"),
        command_cap("session record start", ["offline"], "available"),
        command_cap("session record status", ["offline"], "available"),
        command_cap("session record stop", ["offline"], "available"),
        command_cap("session record step", ["offline", "device"], "available"),
        command_cap("session record candidates", ["offline"], "available"),
        command_cap("session record amend", ["offline"], "available"),
        command_cap("session record build-task", ["offline"], "available"),
        command_cap("session record promote", ["offline"], "available"),
        command_cap("record", ["offline"], "available"),
        command_cap("record start", ["offline"], "available"),
        command_cap("record status", ["offline"], "available"),
        command_cap("record stop", ["offline"], "available"),
        command_cap("record step", ["offline", "device"], "available"),
        command_cap("record candidates", ["offline"], "available"),
        command_cap("record amend", ["offline"], "available"),
        command_cap("record build-task", ["offline"], "available"),
        command_cap("record promote", ["offline"], "available"),
        command_cap("current-page", ["device"], "available"),
        command_cap("is-visible", ["device"], "available"),
        command_cap("locate", ["device"], "available"),
        command_cap("tap-target", ["device"], "available"),
        command_cap("navigate", ["device"], "available"),
        command_cap("monitor --once", ["device"], "available"),
        command_cap("monitor", ["device"], "available"),
        command_cap("stream", ["device"], "available"),
        command_cap("scheduler status", ["running_runtime"], "reserved"),
        command_cap("scheduler pause", ["running_runtime"], "reserved"),
        command_cap("scheduler resume", ["running_runtime"], "reserved"),
        command_cap("scheduler start", ["running_runtime"], "reserved"),
        command_cap("scheduler stop", ["running_runtime"], "reserved"),
        command_cap("lab validate", ["offline"], "available"),
        command_cap("lab run", ["device"], "available"),
        command_cap("capture", ["device"], "available"),
        command_cap("capture diagnose", ["device"], "available"),
        command_cap("detect", ["device"], "available"),
        command_cap("env resolve", ["offline"], "available"),
        command_cap("env status", ["offline"], "available"),
        command_cap("detect-page", ["device"], "available"),
        command_cap("recognize", ["device"], "available"),
        command_cap(
            "operation dry-run",
            ["running_runtime", "device"],
            "reserved",
        ),
        command_cap(
            "operation run",
            ["running_runtime", "device", "lab_lease"],
            "blocked_until_lab_lease",
        ),
        command_cap(
            "control probe-click",
            ["running_runtime", "device", "lab_lease"],
            "blocked_until_lab_lease",
        ),
        command_cap(
            "package run",
            ["running_runtime", "device", "lab_lease"],
            "blocked_until_lab_lease",
        ),
    ];
    commands.extend(runtime_debug::capabilities());
    commands
}

pub(crate) fn command_cap<I>(command: &str, needs: I, status: &str) -> Value
where
    I: IntoIterator,
    I::Item: Into<String>,
{
    json!({
        "command": command,
        "needs": needs.into_iter().map(Into::into).collect::<Vec<String>>(),
        "status": status
    })
}
